# Generated by Django 5.1.2 on 2024-10-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='arrival_time_at_destination',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='train',
            name='arrival_time_at_source',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='train',
            name='destination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='train',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_name',
            field=models.CharField(max_length=255),
        ),
    ]
