# Generated by Django 5.1.2 on 2024-10-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_train_arrival_time_at_destination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='total_seats',
            new_name='seat_capacity',
        ),
    ]
