# Generated by Django 5.1.2 on 2024-10-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_total_seats_train_seat_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default='aac3170f-506f-4dd7-8', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_seats',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_numbers',
            field=models.TextField(default=5),
        ),
    ]
