# Generated by Django 5.1.2 on 2024-10-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_booking_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_numbers',
            field=models.TextField(default=''),
        ),
    ]
