# Generated by Django 5.1.2 on 2024-10-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_booking_booking_id_alter_booking_seat_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_numbers',
            field=models.JSONField(),
        ),
    ]
